services:
  app:
    build:
      context: ./php
    container_name: learning_app
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: learning_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: learning_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lms-bms
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: learning_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123
    networks:
      - laravel

  node:
    image: node:20
    container_name: learning_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:

volumes:
  db_data:
